"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2quj$jcn=5p$yuqcxl!4r9q8fe*2n)k&ss8o=i_g5nlw%w!lsx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Django admin theme


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    #'rest_framework',
    #'corsheaders',


    #Apps
    'api',
    'applications',
    'users',
    'reviews',
    'notifications',
    'scholarships',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

AUTH_USER_MODEL = 'users.User'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




# Jazzmin settings
JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "EB-SB",
    
    # Title on the login screen
    "site_header": "EB-SB",
    
    # Title on the brand (upper left)
    "site_brand": "Scholarship Board",
    
    # Logo to use for your site
    "site_logo": None, #"images/scholarship_logo.png",
    
    # Logo to use for login form
    "login_logo": None,
    
    # CSS classes for the logo
    "site_logo_classes": "img-circle",
    
    # Relative path to favicon
    "site_icon": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Ebonyi State Scholarship Board",
    
    # Copyright on the footer
    "copyright": "FON Scholars 2025",
    
    # The model admin to search from the search bar
    "search_model": "users.User",
    
    # Field name on the user model that contains the avatar
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Links to put along the top menu
    "topmenu_links": [
        # Url that gets reversed (Permissions can be added)
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        
        # External url that opens in a new window (Permissions can be added)
        {"name": "Support", "url": "https://example.com/support", "new_window": True},
        
        # Model admin to link to (Permissions checked against model)
        {"model": "users.User"},
        
        # App with dropdown menu to all its models pages
        {"app": "scholarships"},
    ],
    
    #############
    # User Menu #
    #############
    
    # Additional links to include in the user menu
    "usermenu_links": [
        {"name": "Support", "url": "https://example.com/support", "new_window": True},
        {"model": "users.User"}
    ],
    
    #############
    # Side Menu #
    #############
    
    # Whether to display the side menu
    "show_sidebar": True,
    
    # Whether to aut expand the menu
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu
    "hide_apps": [],
    
    # Hide these models when generating side menu
    "hide_models": [],
    
    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": [
        "users", 
        "users.User", 
        "users.UserProfile",
        "scholarships",
        "scholarships.ScholarshipCategory",
        "scholarships.Scholarship",
        "applications",
        "applications.Application",
        "applications.Document",
        "reviews",
        "reviews.Review",
        "notifications",
        "notifications.Notification",
        "notifications.NotificationPreference",
        "auth",
    ],
    
    # Custom icons for side menu apps/models
    "icons": {
        "users": "fas fa-users-cog",
        "users.user": "fas fa-user",
        "users.userprofile": "fas fa-id-card",
        "scholarships": "fas fa-graduation-cap",
        "scholarships.scholarshipcategory": "fas fa-list",
        "scholarships.scholarship": "fas fa-award",
        "applications": "fas fa-file-alt",
        "applications.application": "fas fa-file-signature",
        "applications.document": "fas fa-file-upload",
        "reviews": "fas fa-check-circle",
        "reviews.review": "fas fa-star",
        "notifications": "fas fa-bell",
        "notifications.notification": "fas fa-envelope",
        "notifications.notificationpreference": "fas fa-cog",
        "auth.group": "fas fa-users",
    },
    
    # Custom icons for side menu apps/models when the side menu is collapsed
    "icons_small": {
        "users": "fas fa-users-cog",
        "scholarships": "fas fa-graduation-cap",
        "applications": "fas fa-file-alt",
        "reviews": "fas fa-check-circle",
        "notifications": "fas fa-bell",
    },
    
    # Each list item in the side menu consists of a dictionary
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts
    "custom_css": None,
    "custom_js": None,
    
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    
    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs
    "changeform_format": "horizontal_tabs",
    
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "users.user": "collapsible",
        "users.userprofile": "vertical_tabs",
        "applications.application": "collapsible",
    },
    
    # Add a language dropdown to the admin
    "language_chooser": False,
}

# UI Theme settings
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}